### ISSUE TITLE
Is meeting the timing requirements possible?

### ISSUE THREAD

**Issue by Hoernchen** [enjoy-digital/colorlite#10]
I'm currently trying to bring up a 8.2 board, and I can only find a working seed by reducing the sysclock to 40Mhz - apparently much older versions of litex/this repo (pre 32 bit eth data path) were able to easily reach the sysclock timing reqs, but failed for the 125Mhz eth clock. I've tried a few older toolchain releases, too.

What is the proper approach here? Did 50Mhz ever work?

I'm asking because so far Ethernet is not stable on 8.2 (see https://github.com/enjoy-digital/colorlite/issues/8) so my first step was to ensure I do not end up with timing violations, which is already difficult enough...

**Comment by Hoernchen** [comment]
Fixed by https://github.com/enjoy-digital/colorlite/commit/2844a5288c9468e6efd098b93847bbdb50ae6d21

**Comment by rowanG077** [comment]
I broke up the datapath a bit in https://github.com/enjoy-digital/liteeth/pull/151 In my application I can't just reduce frequency to 40Mhz. With that it reaches 50Mhz with ease.
