### ISSUE TITLE
Flash Read ID command not working

### ISSUE THREAD

**Issue by derekmulcahy** [enjoy-digital/colorlite#3]
Hi,

I think that the value for the READ_ID command should be 0x9F and not 0x9E in scripts/test_flash.py

0x9E returns 00000000
0x9F returns 00ef4016

0x9F is documented on page 48 of the gd25q16c_v3.0_20181204.pdf in the chubby75 repo and EF4016 looks very reasonable for a Winbond chip.

Thanks for putting this together. It really helped me understand what etherbone is and it has got me past Blinky!

Cheers,
Derek

**Comment by enjoy-digital** [comment]
Thanks for the feedback and reporting the issue. This has been fixed with https://github.com/enjoy-digital/colorlite/commit/e52da43b4f91eaea82d97710bf0b5ef4b9e84593.
