### ISSUE TITLE
Doesn't support V8.0 boards

### ISSUE THREAD

**Issue by RGD2** [enjoy-digital/colorlite#7]
worked around with: 

```diff
--- a/colorlite.py
+++ b/colorlite.py
@@ -60,8 +60,8 @@ class _CRG(Module):
 # ColorLite ----------------------------------------------------------------------------------------
 
 class ColorLite(SoCMini):
-    def __init__(self, sys_clk_freq=int(50e6), with_etherbone=True, ip_address=None, mac_address=None):
-        platform     = colorlight_5a_75b.Platform(revision="7.0")
+    def __init__(self, sys_clk_freq=int(50e6), with_etherbone=True, ip_address='192.168.0.64', mac_address=None):
+        platform     = colorlight_5a_75b.Platform(revision="8.0")
 
         # CRG --------------------------------------------------------------------------------------
         self.submodules.crg = _CRG(platform, sys_clk_freq)
```

This **seems** to work, but I am having another issue, unsure if related

**Comment by RGD2** [comment]
Note, was also changing IP address, so this isn't quite right for a patch.

I think it's okay to just leave this open for now. 

At most, can make a branch that has a single diff *like* the above in it, but for just the `platform = ...` line, and just keep rebasing it to master, then checking it out to 'enable' V8.0 support... rather than rewriting colorlight.py to include some flag swtiching to switch between, as I think it's better left clean .

could maybe mention in the README it only works 'out of the box' with a V7.0 board though. 

Or just leave this ticket open forever so the workaround is noticable for new users. It only needs changing a `7` to an `8`, or at least so it appears (for now, see #8)

**Comment by enjoy-digital** [comment]
@RGD2: The project indeed only supports revision `7.0` of the board. I added a note with https://github.com/enjoy-digital/colorlite/commit/1b5ff093687e2266f36312f15ae6554d5f0a4f20 to help user adapting the project to other revisions, but since I don't have them and that these revisions would require testing and eventual adjustments, I prefer to just officially support the 7.0 revision.
